import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { describe, expect, it } from "vitest";

// These exercise the comparison CLI, not a remote database. The checked-in
// baseline is generated by the independent-connection PostgreSQL runner.
describe("schema fingerprint comparison", () => {
  function compare(change: (fingerprint: Record<string, unknown>) => unknown) {
    const directory = mkdtempSync(path.join(tmpdir(), "avana-schema-"));
    try {
      const baseline = JSON.parse(readFileSync("docs/security/phase2/local-schema.json", "utf8"));
      const remote = path.join(directory, "candidate.json");
      writeFileSync(remote, JSON.stringify(change(structuredClone(baseline))));
      return spawnSync(
        process.execPath,
        ["scripts/compare-supabase-schema.mjs", "docs/security/phase2/local-schema.json", remote],
        { encoding: "utf8", windowsHide: true },
      );
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  }
  it("accepts an identical schema exported by the SQL editor", () => {
    const result = compare((fingerprint) => [{ fingerprint }]);
    expect(result.status).toBe(0);
    expect(JSON.parse(result.stdout).equal).toBe(true);
  });
  it("fails on disabled RLS", () => {
    const result = compare((fingerprint) => ({
      ...fingerprint,
      "table:orders": { rls: false, force_rls: false },
    }));
    expect(result.status).toBe(1);
    expect(JSON.parse(result.stdout).differences).toContainEqual({
      key: "table:orders",
      change: "different",
    });
  });
  it("fails on a missing privileged function", () => {
    const result = compare((fingerprint) => {
      delete fingerprint["function:revoke_admin_session(text)"];
      return fingerprint;
    });
    expect(result.status).toBe(1);
    expect(
      JSON.parse(result.stdout).differences.some(
        (entry: { change: string }) => entry.change === "missing_on_staging",
      ),
    ).toBe(true);
  });
  it("fails on malformed or empty metadata", () => {
    const result = compare(() => ({}));
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("Schema comparison failed");
  });
});
